### ISSUE TITLE
Data not matching other sources of ATLAS photometry on same object, off by 2+ magnitudes

### ISSUE THREAD

**Issue by emirkmo** [lukeshingles/atlasserver#22]
For example, photometry of [SN 2022ans](https://fallingstar-data.com/forcedphot/queue/158719/) does not match the same transient's light curve from non-public (e.g., PESSTO) forced phot of the same location/transient, nor the reported public ATLAS photometry from TNS. We double checked the forced phot coordinates and they are an exact match. So we don't understand why the public forced phot is so much worse.

We just checked several TNS classified Ia's and confirmed this in most of them. See a few more examples below. It's not isolated to just a few however. We have seen it in most light curves we have looked at recently. However, as far as we can recall, this did not use to be the case in the past (maybe 1 month ago?)

This issue is being opened by me on behalf of a group of astronomers who noticed the discrepancy when comparing targets. Could you tell us why there is such a difference? And whether it would be possible to fix it?

**Many of these seem much brighter in the public phot, sometimes by ~2 mag**. In addition, the public phot often seems to show a very different LC (such as flat instead of rising). But even for those that are rising in both public and private, there is an offset. We took notice because many Type Ia's we've been following seemed to be superluminous according to the public ATLAS phot. I think this occured recently, maybe ~2 weeks ago? But we cannot be sure. This seem to also lead to a disrepancy between the reported photometry on TNS and the ones obtained from falling-star.

Some more cases of TNS Ia's that clearly have wrong photometry, which do not match other ATLAS photometry:

 - SN 2022rv: https://fallingstar-data.com/forcedphot/queue/152674/ 
 - SN 2022afh: https://fallingstar-data.com/forcedphot/queue/155283/ 
 
 Note, the SN 2022afh is likely having issues with the template? Most are not completely wrong like this. However, you can see the inconsistency with the photometry reported on TNS even for SN 2022rv. There is a 2 magnitude difference. Let me know and I can put together more examples if they are helpful. We found dozens.
 
 Just to re-iterate, the biggest concern for us is the large shift in reported magnitude. With ZTF currently down ATLAS is a main source of SN candidates but getting the wrong photometry by 1-2 mag from the forced phot website makes it difficult to trigger follow-up. We know that in the future the lightcurves could be cleaned up.

Please let me know if you would rather follow up via email. Just wanted to report this to bring it to your attention @lukeshingles.

**Comment by genghisken** [comment]
Hi! We're very glad to see you using the ATLAS forced photometry data. We definitely prefer Github to followup questions like this. It means we can track any required work.

In all the examples above, the "reduced" checkbox was set when the forced photometry was requested. This means you're getting the flux from the INPUT image, NOT the DIFFERENCE image.  Apologies if this is not clear on the interface. Leave the box unchecked if you want difference flux. The forced photometry used by PESSTO is from the difference images.  (It's also stacked.)  If you check the "reduced" box your result will be contaminated by host flux, which is why you're seeing data which is much brighter than you expect. (Input image flux is very useful if the template gets changed during the time the transient was active, or the object is far from the host and you want to follow for a long period of time.)

For the above, I assume you mean 2022afg.  I reran the forced phot for 2022afg and 2022rv with the "reduced" box unchecked (the default option). See:
https://fallingstar-data.com/forcedphot/queue/158725/
and
https://fallingstar-data.com/forcedphot/queue/158727/

Feel free to try a few and get back to us to confirm all is OK or not.  Note that you might not see the same number of points on the lightcurve as in PESSTO because the new Southern ATLAS Telescopes (S. Africa and Chile) are not fully integrated into the forced photometry server (though the data is present for PESSTO). This is not deliberate - the data will be public soon. The southern telescopes are still being commissioned.

**Comment by emirkmo** [comment]
Thank you for getting back so quickly. Looks like it was our mistake. We though difference images were for variable stars. And we are eagerly awaiting the integration of the southern telescopes. I will reopen if we notice any other major systematic differences, outside of public/private/stacking etc.
